### ISSUE TITLE
noospheric mindswap is permanent

### ISSUE THREAD

**Issue by deltanedas** [arcadia-station/arcadia-station#1094]
## Description
mindswap from noospheric event can't be reverted
happened to (at least 1) non-psionic that was swapped, other person mightve been non-psionic as well

**Reproduction**
1. high glimmer
2. hope for the best
3. get swapped with someone
4. the button does nothing

**Screenshots**
doesnt really help, cooldown is off thats all that matters really

**Comment by Elijahrane** [comment]
was able to reproduce, was introduced by one of the changes in mind system I think

Trace:
```
[FATL] unhandled: System.ArgumentException: Visit target already has a session. (Parameter 'entity')
   at Content.Server.Mind.Mind.TransferTo(Nullable`1 entity, Boolean ghostCheckOverride) in /home/rane/Develop/Nyanotrasen/Content.Server/Mind/Mind.cs:line 342
   at Content.Server.Abilities.Psionics.MindSwapPowerSystem.Swap(EntityUid performer, EntityUid target, Boolean end) in /home/rane/Develop/Nyanotrasen/Content.Server/Nyanotrasen/Abilities/Psionics/Abilities/MindSwapPowerSystem.cs:line 159
   at Content.Server.Abilities.Psionics.MindSwapPowerSystem.OnPowerReturned(EntityUid uid, MindSwappedComponent component, MindSwapPowerReturnActionEvent args) in /home/rane/Develop/Nyanotrasen/Content.Server/Nyanotrasen/Abilities/Psionics/Abilities/MindSwapPowerSystem.cs:line 113
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass47_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 252
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass58_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 390
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args, Boolean dispatchByReference) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 551
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast, Boolean byRef) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 219
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent(EntityUid uid, Object args, Boolean broadcast) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 188
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent(EntityUid uid, Object args, Boolean broadcast) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 133
   at Content.Shared.Actions.SharedActionsSystem.PerformAction(EntityUid performer, ActionsComponent component, ActionType action, BaseActionEvent actionEvent, TimeSpan curTime, Boolean predicted) in /home/rane/Develop/Nyanotrasen/Content.Shared/Actions/SharedActionsSystem.cs:line 280
   at Content.Shared.Actions.SharedActionsSystem.OnActionRequest(RequestPerformActionEvent ev, EntitySessionEventArgs args) in /home/rane/Develop/Nyanotrasen/Content.Shared/Actions/SharedActionsSystem.cs:line 205
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 169
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 309
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 255
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__10_0(Object _, Object systemMsg) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 48
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 243
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 145
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Server/BaseServer.cs:line 680
   at Robust.Server.BaseServer.<SetupMainLoop>b__61_1(Object sender, FrameEventArgs args) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Server/BaseServer.cs:line 502
   at Robust.Shared.Timing.GameLoop.Run() in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 213
   at Robust.Server.BaseServer.MainLoop() in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Server/BaseServer.cs:line 529
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Server/Program.cs:line 78
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Server/Program.cs:line 46
   at Robust.Server.ContentStart.Start(String[] args) in /home/rane/Develop/Nyanotrasen/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/rane/Develop/Nyanotrasen/Content.Server/Program.cs:line 9```

**Comment by Leander-0** [comment]
IMO the noospheric mindswap should be permanent, not only happens when glimmer is at the 900 threshold but it acts as a fail state where the whole EPI department badly managed the glimmer, the same way as if the whole station loses power for a long period of time for badly managing the AME.

**Comment by Elijahrane** [comment]
that's a separate issue from this one literally caused by a regression

**Comment by Leander-0** [comment]
ok, this also affects the normal mindswap power i believe.
